### ISSUE TITLE
dump-csum patch doesn't work with btrfs-progs 5.12

### ISSUE THREAD

**Issue by automorphism88** [Lakshmipathi/dduper#56]
Or, rather, it applies, but compilation fails with an error about too many arguments to `open_ctree_fs_info`.

**Comment by Lakshmipathi** [comment]
Thanks, I think CI also catches this issue: https://gitlab.com/giis/dduper/-/jobs/1268979391 Let me check, hopefully its a minor change.

**Comment by Lakshmipathi** [comment]
@automorphism88  Can you try https://github.com/Lakshmipathi/dduper/tree/master/patch/btrfs-progs-v5.12.1 patch? I think it works as per CI job: https://gitlab.com/giis/dduper/-/jobs/1270400624
